all:
	pdflatex main.tex
	pdflatex main.tex
	rm *.snm *.toc *.nav *.aux *.log *.out

test:
	pdflatex test.tex
	rm *.snm *.toc *.nav *.aux *.log *.out
	
test2:
	pdflatex test2.tex
	pdflatex test2.tex
	rm *.snm *.toc *.nav *.aux *.log *.out
