
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '4EE05CAE6D3B98D20D6E82EC4FC867AF'
    
_lr_action_items = {'OPENBRACKET':([3,],[5,]),'RANGE':([2,],[3,]),'NUMBER':([4,5,6,8,],[-2,-3,7,9,]),'NAME':([0,],[2,]),'COMMA':([7,],[8,]),'CLOSEPAREN':([9,],[11,]),'CLOSEBRACKET':([9,],[10,]),'$end':([1,10,11,12,],[0,-5,-4,-1,]),'OPENPAREN':([3,],[4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'closer':([9,],[12,]),'rang':([0,],[1,]),'opener':([3,],[6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> rang","S'",1,None,None,None),
  ('rang -> NAME RANGE opener NUMBER COMMA NUMBER closer','rang',7,'p_Rangeobj','parse_ranges.py',25),
  ('opener -> OPENPAREN','opener',1,'p_opener','parse_ranges.py',38),
  ('opener -> OPENBRACKET','opener',1,'p_opener','parse_ranges.py',39),
  ('closer -> CLOSEPAREN','closer',1,'p_closer','parse_ranges.py',44),
  ('closer -> CLOSEBRACKET','closer',1,'p_closer','parse_ranges.py',45),
]
